/**
 * Base type definitions for the AI Voice & Text Roleplay language app.
 *
 * These interfaces are the single source of truth ("contract") shared across
 * the UI layer (components, stores, hooks) and the data/AI layer.
 * Keep them framework-agnostic: no React/Next.js imports here.
 */

/* ========================================================================== */
/*  Primitive unions                                                          */
/* ========================================================================== */

/** Languages used in the app: `en` = target practice language, `fa` = UI/native. */
export type LanguageCode = 'en' | 'fa';

/** Common European Framework level, used for difficulty & progression. */
export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export type MessageRole = 'user' | 'assistant' | 'system';

/** How a message was produced. */
export type MessageMode = 'text' | 'voice';

/** Category of an inline teaching note attached to a user message. */
export type FeedbackType =
  | 'grammar'
  | 'pronunciation'
  | 'vocabulary'
  | 'idiom'
  | 'style';

/** How urgent the feedback is — drives its visual styling. */
export type FeedbackSeverity = 'info' | 'suggestion' | 'correction';

/* ========================================================================== */
/*  Scenario                                                                  */
/* ========================================================================== */

export type ScenarioCategory =
  | 'travel'
  | 'work'
  | 'daily'
  | 'social'
  | 'education'
  | 'business'
  | 'medical'
  | 'shopping';

/** A real-world situation the user roleplays through with the AI. */
export interface Scenario {
  id: string;
  title: string;
  description: string;
  category: ScenarioCategory;
  /** Lucide icon name used on the scenario card. */
  icon: string;
  /** Recommended difficulty / minimum CEFR level. */
  difficulty: CEFRLevel;
  /** The language being practiced. */
  language: LanguageCode;
  tags: string[];
  /** The AI's character in this scenario. */
  role: ScenarioRole;
  /** Opening line spoken by the AI to kick off the roleplay. */
  opening: string;
  /** Conversation goals the user should try to achieve. */
  objectives: string[];
  /** Useful vocabulary the user might need. */
  vocabulary?: ScenarioVocab[];
  /** Estimated session length, used for stats and UI hints. */
  estimatedMinutes: number;
  /** Premium-gated scenario flag. */
  isPremium?: boolean;
}

export interface ScenarioRole {
  /** e.g. "Job Interviewer", "Barista", "Airport Officer". */
  name: string;
  /** Personality/system-prompt description for the AI. */
  persona: string;
  /** Optional avatar image path or emoji. */
  avatar?: string;
}

export interface ScenarioVocab {
  term: string;
  /** Meaning shown in the user's native language (fa). */
  meaning: string;
  example?: string;
}

/* ========================================================================== */
/*  Chat Message                                                              */
/* ========================================================================== */

/** A single message in a roleplay conversation. */
export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  mode: MessageMode;
  language: LanguageCode;
  /** Epoch milliseconds. */
  createdAt: number;
  /** Teaching notes attached to a user message. */
  feedback?: Feedback[];
  /** Raw recognized speech before cleanup (voice mode only). */
  rawTranscript?: string;
  /** STT recognition confidence, 0–1 (voice mode only). */
  confidence?: number;
  /** Object URL of recorded audio (voice mode only). */
  audioUrl?: string;
  status?: 'sending' | 'sent' | 'error';
}

/* ========================================================================== */
/*  Feedback                                                                  */
/* ========================================================================== */

/** A non-intrusive, inline teaching note generated by the AI. */
export interface Feedback {
  id: string;
  type: FeedbackType;
  severity: FeedbackSeverity;
  /** The problematic segment from the user's message. */
  original: string;
  /** Suggested correction / better phrasing. */
  suggestion: string;
  /** Short explanation, localized for the user. */
  explanation: string;
  /** Character range in the original message, for inline highlighting. */
  range?: { start: number; end: number };
}

/* ========================================================================== */
/*  User Stats                                                                */
/* ========================================================================== */

/** Aggregated progress and activity metrics for a user. */
export interface UserStats {
  userId: string;
  totalSessions: number;
  totalMessages: number;
  totalPracticeMinutes: number;
  /** Number of days in a row the user has practiced. */
  streakDays: number;
  /** ISO date string (YYYY-MM-DD). */
  lastActiveDate: string;
  /** Rolling count of each feedback type the user has received. */
  feedbackReceived: Record<FeedbackType, number>;
  /** Estimated current proficiency level. */
  currentLevel: CEFRLevel;
  weeklyGoalMinutes: number;
  weeklyProgressMinutes: number;
  /** Scenarios finished, with the best score kept. */
  completedScenarios: CompletedScenario[];
  /** New words/expressions learned (unique suggestions accepted/noted). */
  wordsLearned: string[];
  /** Overall gamification points. */
  totalPoints: number;
}

export interface CompletedScenario {
  scenarioId: string;
  /** Epoch milliseconds. */
  completedAt: number;
  /** 0–100 performance score. */
  score: number;
  messagesCount: number;
}

/* ========================================================================== */
/*  AI Config                                                                 */
/* ========================================================================== */

export type AIProvider = 'openai' | 'anthropic' | 'gemini' | 'custom';

/** Configuration for the AI service. Kept on the server; `apiKey` never ships to the client. */
export interface AIConfig {
  provider: AIProvider;
  model: string;
  /** Server-side only — resolved from environment, never exposed to the browser. */
  apiKey?: string;
  /** Base URL for custom / open-source providers. */
  baseUrl?: string;
  /** Creativity, 0–1. */
  temperature: number;
  maxTokens: number;
  /** Template scaffolded into the system prompt at request time. */
  systemPromptTemplate: string;
  /** Whether to stream responses back to the client. */
  streaming: boolean;
  /** Whether live inline feedback generation is enabled. */
  feedbackEnabled: boolean;
  targetLanguage: LanguageCode;
  userLevel: CEFRLevel;
}

/* ========================================================================== */
/*  Chat Session (store-level)                                                */
/* ========================================================================== */

export type SessionStatus = 'active' | 'paused' | 'completed';

/** An in-progress or finished roleplay session, owned by the chat store. */
export interface ChatSession {
  id: string;
  scenarioId: string;
  messages: ChatMessage[];
  /** Epoch milliseconds. */
  startedAt: number;
  status: SessionStatus;
  mode: MessageMode;
}

/* ========================================================================== */
/*  Curriculum / Learning Tree                                                 */
/* ========================================================================== */

/** CEFR levels plus A0 for absolute beginners. Ordered low → high. */
export type CurriculumLevel = 'A0' | CEFRLevel;

/** Type of a teachable unit in the learning tree. */
export type LessonType =
  | 'alphabet'      // sounds, letters (A0)
  | 'vocab'         // vocabulary sets
  | 'phrase'        // common phrases / dialogs
  | 'grammar'       // a grammar point
  | 'roleplay'      // a scenario conversation (links to a Scenario)
  | 'challenge';    // a mixed skill challenge

/** One node in the learning tree. */
export interface Lesson {
  id: string;
  title: string;
  /** Short, motivating Persian description. */
  description: string;
  type: LessonType;
  level: CurriculumLevel;
  /** Lucide icon name shown on the card. */
  icon: string;
  /** For roleplay lessons: the linked scenario id (starts a chat). */
  scenarioId?: string;
  /** Estimated minutes to complete. */
  estimatedMinutes: number;
  /** True when the lesson is locked until prerequisites are done. */
  locked?: boolean;
}

/** A stage groups lessons by level (A0, A1, ...). */
export interface CurriculumStage {
  level: CurriculumLevel;
  /** Persian label, e.g. «صفر مطلق». */
  label: string;
  /** One-line motivating subtitle. */
  subtitle: string;
  /** Lucide icon name for the stage badge. */
  icon: string;
  /** Accent color token name used on the stage header. */
  accent: 'sky' | 'emerald' | 'amber' | 'violet' | 'rose' | 'cyan';
  /** Optional grouping into themed Units (used by A0's 4 units). */
  units?: CurriculumUnit[];
  lessons: Lesson[];
}

/** A themed unit within a stage (e.g. "الفبا و احوالپرسی"). */
export interface CurriculumUnit {
  id: string;
  /** Persian unit title. */
  title: string;
  /** Short motivating Persian subtitle. */
  subtitle: string;
  /** Lucide icon name. */
  icon: string;
  lessons: Lesson[];
}

/* ========================================================================== */
/*  Interactive Lesson content (the 4-step flow)                              */
/* ========================================================================== */

/** A vocabulary flashcard with audio + Persian meaning + example. */
export interface VocabCard {
  /** The English word/phrase to learn. */
  term: string;
  /** Phonetic spelling hint, e.g. "hə-ˈlō". */
  phonetic?: string;
  /** Persian meaning. */
  meaning: string;
  /** Short English example sentence. */
  example: string;
  /** Lucide icon or emoji for the card face. */
  emoji?: string;
}

/** A one-line, friendly grammar explanation. */
export interface GrammarByte {
  /** The pattern/rule, shown prominently. e.g. "I am + name". */
  rule: string;
  /** One-line friendly Persian explanation. */
  explanation: string;
  /** 1–3 example sentences showing the rule. */
  examples: string[];
}

/** Type of an interactive practice question. */
export type QuizKind = 'multiple-choice' | 'word-order';

/** A single interactive practice question. */
export interface QuizQuestion {
  id: string;
  kind: QuizKind;
  /** The prompt in Persian. */
  prompt: string;
  /** The English phrase shown when needed. */
  englishHint?: string;
  /** For multiple-choice: the options; for word-order: the words to arrange. */
  options?: string[];
  /** For word-order: shuffled words. */
  words?: string[];
  /** Index of the correct option (multiple-choice). */
  correctIndex?: number;
  /** The correct arranged sentence (word-order). */
  correctSentence?: string;
  /** Friendly Persian explanation shown after answering. */
  explain: string;
}

/** The full interactive content of a non-roleplay lesson. */
export interface LessonContent {
  lessonId: string;
  /** Step 1: Vocabulary flashcards. */
  vocabulary: VocabCard[];
  /** Step 2: A grammar micro-explanation. */
  grammar: GrammarByte;
  /** Step 3: Practice questions. */
  quiz: QuizQuestion[];
  /** Step 4: a roleplay scenario id for the live AI practice (optional). */
  practiceScenarioId?: string;
  /** Optional free-text prompt used for a short AI practice turn. */
  practicePrompt?: string;
}

/** Names of the 4 steps in the lesson flow. */
export type LessonStep = 'vocab' | 'grammar' | 'quiz' | 'practice';

/* ========================================================================== */
/*  Podcasts / Audio Stories (Listening practice)                             */
/* ========================================================================== */

/** A single sentence in a story's transcript. */
export interface TranscriptLine {
  /** The English sentence. */
  en: string;
  /** Persian translation. */
  fa: string;
}

/** A multiple-choice comprehension question about a story. */
export interface StoryQuizQuestion {
  id: string;
  /** The prompt in Persian. */
  prompt: string;
  options: string[];
  /** Index of the correct option. */
  correctIndex: number;
  /** Friendly Persian explanation. */
  explain: string;
}

/** A leveled audio story for the Podcasts section. */
export interface Story {
  id: string;
  /** Persian title shown on the card. */
  title: string;
  /** One-line Persian hook. */
  description: string;
  /** Lucide icon or emoji. */
  emoji: string;
  /** CEFR level the story is graded to. */
  level: CurriculumLevel;
  /** Rough minutes to listen. */
  estimatedMinutes: number;
  /** The story transcript, sentence-by-sentence. */
  lines: TranscriptLine[];
  /** Comprehension quiz at the end (3 questions). */
  quiz: StoryQuizQuestion[];
  /** Accent tag for discoverability. */
  tags: string[];
}

/* ========================================================================== */
/*  Grand Mastery Exam & Certification                                        */
/* ========================================================================== */

/** Accent used by a listening task's TTS narration. */
export type ExamAccent = 'us' | 'uk';

/** A multiple-choice question (used in Listening & Use of English). */
export interface ExamQuestion {
  id: string;
  /** Persian prompt. */
  prompt: string;
  /** English options (rendered LTR-isolated). */
  options: string[];
  /** Index of the correct option. */
  correctIndex: number;
}

/** Section 1 — a listening task narrated by TTS in a given accent. */
export interface ExamListeningTask {
  id: string;
  accent: ExamAccent;
  /** Persian scene-setting line, e.g. «پیام اعلام فرودگاه». */
  context: string;
  /** The English passage the TTS reads aloud. */
  passage: string;
  questions: ExamQuestion[];
}

/** Section 3 — arrange shuffled words into the correct sentence. */
export interface ExamSentenceTask {
  id: string;
  /** Persian instruction. */
  prompt: string;
  /** Words in the correct order (shuffled for display). */
  words: string[];
  /** The correct full sentence (compared via normalizeText). */
  correctSentence: string;
}

/** Section 4 — one examiner question in the oral interview. */
export interface ExamOralQuestion {
  id: string;
  /** Cognitive level of the question. */
  tier: 'describe' | 'analyze' | 'evaluate';
  /** The English question (read aloud by TTS). */
  question: string;
  /** Persian translation shown beneath. */
  questionFa: string;
}

/** The full Grand Mastery Exam content. */
export interface MasteryExam {
  listening: ExamListeningTask[];
  useOfEnglish: ExamQuestion[];
  syntax: ExamSentenceTask[];
  oral: ExamOralQuestion[];
}

/** Per-section scores of a completed exam attempt. */
export interface ExamSectionScores {
  listening: number;   // 0–100
  useOfEnglish: number; // 0–100
  syntax: number;       // 0–100
  oral: number;         // 0–100
  total: number;        // 0–100 weighted
}

/** Maps a total percentage to a CEFR-equivalent label. */
export function cefrFromScore(total: number): { level: string; label: string } {
  if (total >= 90) return { level: 'C2', label: 'تسلط کامل — Mastery' };
  if (total >= 75) return { level: 'C1', label: 'پیشرفته — Advanced' };
  if (total >= 60) return { level: 'B2', label: 'متوسط پیشرفته — Vantage' };
  if (total >= 45) return { level: 'B1', label: 'متوسط — Threshold' };
  if (total >= 30) return { level: 'A2', label: 'پیش‌متوسطه — Waystage' };
  return { level: 'A1', label: 'مقدماتی — Breakthrough' };
}



