/**
 * Base type definitions for the AI Voice & Text Roleplay language app.
 *
 * These interfaces are the single source of truth ("contract") shared across
 * the UI layer (components, stores, hooks) and the data/AI layer.
 * Keep them framework-agnostic: no React/Next.js imports here.
 */

/* ========================================================================== */
/*  Primitive unions                                                          */
/* ========================================================================== */

/** Languages used in the app: `en` = target practice language, `fa` = UI/native. */
export type LanguageCode = 'en' | 'fa';

/** Common European Framework level, used for difficulty & progression. */
export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export type MessageRole = 'user' | 'assistant' | 'system';

/** How a message was produced. */
export type MessageMode = 'text' | 'voice';

/** Category of an inline teaching note attached to a user message. */
export type FeedbackType =
  | 'grammar'
  | 'pronunciation'
  | 'vocabulary'
  | 'idiom'
  | 'style';

/** How urgent the feedback is — drives its visual styling. */
export type FeedbackSeverity = 'info' | 'suggestion' | 'correction';

/* ========================================================================== */
/*  Scenario                                                                  */
/* ========================================================================== */

export type ScenarioCategory =
  | 'travel'
  | 'work'
  | 'daily'
  | 'social'
  | 'education'
  | 'business'
  | 'medical'
  | 'shopping';

/** A real-world situation the user roleplays through with the AI. */
export interface Scenario {
  id: string;
  title: string;
  description: string;
  category: ScenarioCategory;
  /** Lucide icon name used on the scenario card. */
  icon: string;
  /** Recommended difficulty / minimum CEFR level. */
  difficulty: CEFRLevel;
  /** The language being practiced. */
  language: LanguageCode;
  tags: string[];
  /** The AI's character in this scenario. */
  role: ScenarioRole;
  /** Opening line spoken by the AI to kick off the roleplay. */
  opening: string;
  /** Conversation goals the user should try to achieve. */
  objectives: string[];
  /** Useful vocabulary the user might need. */
  vocabulary?: ScenarioVocab[];
  /** Estimated session length, used for stats and UI hints. */
  estimatedMinutes: number;
  /** Premium-gated scenario flag. */
  isPremium?: boolean;
}

export interface ScenarioRole {
  /** e.g. "Job Interviewer", "Barista", "Airport Officer". */
  name: string;
  /** Personality/system-prompt description for the AI. */
  persona: string;
  /** Optional avatar image path or emoji. */
  avatar?: string;
}

export interface ScenarioVocab {
  term: string;
  /** Meaning shown in the user's native language (fa). */
  meaning: string;
  example?: string;
}

/* ========================================================================== */
/*  Chat Message                                                              */
/* ========================================================================== */

/** A single message in a roleplay conversation. */
export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  mode: MessageMode;
  language: LanguageCode;
  /** Epoch milliseconds. */
  createdAt: number;
  /** Teaching notes attached to a user message. */
  feedback?: Feedback[];
  /** Raw recognized speech before cleanup (voice mode only). */
  rawTranscript?: string;
  /** STT recognition confidence, 0–1 (voice mode only). */
  confidence?: number;
  /** Object URL of recorded audio (voice mode only). */
  audioUrl?: string;
  status?: 'sending' | 'sent' | 'error';
}

/* ========================================================================== */
/*  Feedback                                                                  */
/* ========================================================================== */

/** A non-intrusive, inline teaching note generated by the AI. */
export interface Feedback {
  id: string;
  type: FeedbackType;
  severity: FeedbackSeverity;
  /** The problematic segment from the user's message. */
  original: string;
  /** Suggested correction / better phrasing. */
  suggestion: string;
  /** Short explanation, localized for the user. */
  explanation: string;
  /** Character range in the original message, for inline highlighting. */
  range?: { start: number; end: number };
}

/* ========================================================================== */
/*  User Stats                                                                */
/* ========================================================================== */

/** Aggregated progress and activity metrics for a user. */
export interface UserStats {
  userId: string;
  totalSessions: number;
  totalMessages: number;
  totalPracticeMinutes: number;
  /** Number of days in a row the user has practiced. */
  streakDays: number;
  /** ISO date string (YYYY-MM-DD). */
  lastActiveDate: string;
  /** Rolling count of each feedback type the user has received. */
  feedbackReceived: Record<FeedbackType, number>;
  /** Estimated current proficiency level. */
  currentLevel: CEFRLevel;
  weeklyGoalMinutes: number;
  weeklyProgressMinutes: number;
  /** Scenarios finished, with the best score kept. */
  completedScenarios: CompletedScenario[];
  /** New words/expressions learned (unique suggestions accepted/noted). */
  wordsLearned: string[];
  /** Overall gamification points. */
  totalPoints: number;
}

export interface CompletedScenario {
  scenarioId: string;
  /** Epoch milliseconds. */
  completedAt: number;
  /** 0–100 performance score. */
  score: number;
  messagesCount: number;
}

/* ========================================================================== */
/*  AI Config                                                                 */
/* ========================================================================== */

export type AIProvider = 'openai' | 'anthropic' | 'gemini' | 'custom';

/** Configuration for the AI service. Kept on the server; `apiKey` never ships to the client. */
export interface AIConfig {
  provider: AIProvider;
  model: string;
  /** Server-side only — resolved from environment, never exposed to the browser. */
  apiKey?: string;
  /** Base URL for custom / open-source providers. */
  baseUrl?: string;
  /** Creativity, 0–1. */
  temperature: number;
  maxTokens: number;
  /** Template scaffolded into the system prompt at request time. */
  systemPromptTemplate: string;
  /** Whether to stream responses back to the client. */
  streaming: boolean;
  /** Whether live inline feedback generation is enabled. */
  feedbackEnabled: boolean;
  targetLanguage: LanguageCode;
  userLevel: CEFRLevel;
}

/* ========================================================================== */
/*  Chat Session (store-level)                                                */
/* ========================================================================== */

export type SessionStatus = 'active' | 'paused' | 'completed';

/** An in-progress or finished roleplay session, owned by the chat store. */
export interface ChatSession {
  id: string;
  scenarioId: string;
  messages: ChatMessage[];
  /** Epoch milliseconds. */
  startedAt: number;
  status: SessionStatus;
  mode: MessageMode;
}
